[package]
name = "furuyoni_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34", features = ["full"] }
furuyoni_lib = { path = "../furuyoni_lib" }
rand = "0.8.5"
thiserror = "1.0"
bevy = { version = "0.12" }
bevy_editor_pls = "0.6"
bevy_asset_loader = { version = "0.18" }
iyes_progress = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-lite = "2.0"

