[package]
name = "furuyoni_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
furuyoni_lib = { path = "../furuyoni_lib" }
rand = "0.8.5"
thiserror = "1.0.37"
bevy = { version = "0.9.1", features = ["dynamic"] }
bevy_editor_pls = "0.2.0"
iyes_loopless = { version = "0.9.1" }
bevy_asset_loader = { version = "0.14.1", features = ["stageless", "iyes_progress", "progress_tracking_stageless"] }
iyes_progress = { version = "0.7.1", features = ["iyes_loopless"] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
